# Generated by Django 3.2.9 on 2021-12-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_address', models.TextField()),
                ('client_gst', models.IntegerField(max_length=15)),
                ('biller_name', models.CharField(max_length=100)),
                ('biller_email', models.EmailField(max_length=254)),
                ('biller_address', models.TextField()),
                ('biller_gst', models.IntegerField(max_length=15)),
                ('cost_service', models.IntegerField(max_length=1000)),
                ('tax_rate', models.IntegerField()),
                ('bank_accounts', models.TextField()),
            ],
        ),
    ]
