# Generated by Django 3.2.9 on 2021-12-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_billdetails_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='static/pdf/')),
            ],
        ),
    ]
