# Generated by Django 3.2.9 on 2021-12-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_generatedpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdetails',
            name='list_of_service',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
